# Generated by Django 3.0.7 on 2020-07-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='billing_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=16)),
                ('street', models.TextField()),
                ('street2', models.TextField()),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
